export const SKYPEWEB_HTTPS = 'https://';
export const SKYPEWEB_LOCKANDKEY_APPID = 'msmsgs@msnmsgr.com';
export const SKYPEWEB_LOCKANDKEY_SECRET = 'Q1P7W2E4J9R8U3S5';
export const SKYPEWEB_CLIENTINFO_NAME = 'swx-skype.com';
export const SKYPEWEB_CLIENTINFO_VERSION = '908/1.7.251';
export const SKYPEWEB_CONTACTS_HOST = 'api.skype.com';
export const SKYPEWEB_DEFAULT_MESSAGES_HOST = 'client-s.gateway.messenger.live.com';
export const SKYPEWEB_LOGIN_URL = 'https://login.skype.com/login?method=skype&client_id=578134&redirect_uri=https%3A%2F%2Fweb.skype.com';
export const SKYPEWEB_SELF_DISPLAYNAME_URL = '/users/self/displayname';